[#7]: Update pre-commit

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+# Directories
+GIT_ROOT=$(git rev-parse --show-toplevel)
+SCRIPTS_DIRECTORY=$GIT_ROOT/scripts
+GIT_HOOKS_DIRECTORY=$SCRIPTS_DIRECTORY/git-hooks
+
 # check for commits to protected branches
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
@@ -11,24 +16,38 @@ fi
 # Redirect output to stderr.
 exec 1>&2
 
-# Swiftlint https://woowabros.github.io/tools/2019/08/05/swiftlint-githooks.html
+# Swiftlint https://github.com/aitemr/awesome-git-hooks/blob/master/pre-commit/pre-commit-swiftlint
 LINT=$(which swiftlint)
 
 if [[ -e "${LINT}" ]]; then
-  echo "SwiftLint Start"
+	echo "SwiftLint Start..."
+	echo $(pwd)
 else
-  echo "SwiftLint does not exist, download from https://github.com/realm/SwiftLint"
-  exit 1
+	echo "SwiftLint does not exist, download from https://github.com/realm/SwiftLint"
+	exit 1
 fi
-count=0
 
-targets=$(git diff --stat --cached --diff-filter=d --name-only $(git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD)) | grep -F ".swift")
-addModifiedFile "${targets[0]}" $count
-export -p | grep SCRIPT_INPUT_FILE
-export SCRIPT_INPUT_FILE_COUNT=$count
-RESULT=$($LINT lint --use-script-input-files --config .swiftlint.yml)
+RESULT=$($LINT lint --quiet --config .swiftlint.yml)
+
 if [ "$RESULT" == '' ]; then
-  printf "SwiftLint Finished.\n"
+	printf "SwiftLint Finished.\n"
 else
-  echo ""
-  printf "SwiftLint Failed. Please check below:\n"
+	echo ""
+	printf "SwiftLint Failed. Please check below:\n"
+
+	while read -r line; do
+		FILEPATH=$(echo $line | cut -d : -f 1)
+		L=$(echo $line | cut -d : -f 2)
+		C=$(echo $line | cut -d : -f 3)
+		TYPE=$(echo $line | cut -d : -f 4 | cut -c 2-)
+		MESSAGE=$(echo $line | cut -d : -f 5 | cut -c 2-)
+		DESCRIPTION=$(echo $line | cut -d : -f 6 | cut -c 2-)
+		printf "\n $TYPE\n"
+		printf "    $FILEPATH:$L:$C\n"
+		printf "    $MESSAGE - $DESCRIPTION\n"
+	done <<< "$RESULT"
+
+	printf "\nCOMMIT ABORTED. Please fix them before commiting.\n"
+
+	exit 1
+fi
